### ISSUE TITLE
bug in comment section

### ISSUE THREAD

**Issue by eeid26** [Polymer/core-icon#33]
chrome now imports
```html
    <link rel="import" href="/components/core-icons/core-icons.html">
```
and
```html
    <link rel="import" href="/components/core-icons/communication-icons.html">
```
from the comment section

because they are not commented correctly after the last merge.

**Comment by Mikanoshi** [comment]
+1, had to remove nested comments so vulcanize can strip the main one

**Comment by ebidel** [comment]
This was fixed in https://github.com/Polymer/core-icon/commit/bcf1d7f1fce79a2af93af3c4577eb52c41cf1353. We re-tagged core-icon. Please do a `bower cache clean` and re-install the element.
